version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express_container
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: ${DB_VIEWER_SERVER}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_VIEWER_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_VIEWER_ADMIN_PASSWORD}
      # Basic Authentication
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_VIEWER_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_VIEWER_PASSWORD}
    ports:
      - ${DB_VIEWER_PORT}:${DB_VIEWER_PORT}
    depends_on:
      - mongodb
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher_container
    restart: always
    ports:
      - "${MAILCATCHER_VIEWER_PORT}:${MAILCATCHER_VIEWER_PORT}" 
      - "${MAILCATCHER_PORT}:${MAILCATCHER_PORT}" 

volumes:
  mongodb_data:
