import { Providers } from '@lib/providers';

import './global.css';

export const metadata = {
  title: 'Welcome to apps/front',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Providers>
  );
}
