name: Run Lint
run-name:
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  eslint:
    name: run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node
        uses: actions/setup-node@v4

      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: npm run lint
