name: Run Tests
run-name:
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  tests:
    name: run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}

      - name: Run Tests
        run: npm run test
