name: Run Lint
run-name:
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  frontend-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run lint
