name: Run Lint
run-name:
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  eslint:
    name: run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-yarn
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node
        uses: actions/setup-node@v4

      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Install Dependencies
        run: yarn install

      - name: Cache Nx artifacts 
        id: cache-nx
        uses: actions/cache@v3
        with:
          path: ~/.nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/nx.json') }}

      - if: ${{ steps.cache-nx.outputs.cache-hit != 'true' }}
        name: Install Nx
        run: yarn add -D @nrwl/cli

      - name: Run Lint
        run: npm run lint
